//Category
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

//Search
export const SEARCH_REQUEST = 'SERCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

//Favorite
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const DELETE_FROM_FAVORITE = 'DELETE_FROM_FAVORITE';

//FAVORITE SIDE-BAR
export const ON_FAVORIE_SHOW = 'ON_FAVORIE_SHOW';
export const ON_FAVORIE_HIDE = 'DELETE_FROM_HIDE';
